#! /usr/bin/env fish

source ./bin/activate.fish

function uic -a input output
    pyside6-uic -g python ./RWESharp/ui/uifiles/$input |
        string replace res_rc RWESharp.ui.res_rc |
        string replace BaseModWidgets BaseMod.BaseModWidgets |
        string replace RWESharpWidgets RWS.Widgets >$output
    echo Compiling ./RWESharp/ui/uifiles/$input to $output
end

echo "Compiling resources"
pyside6-rcc -g python -o ./RWESharp/ui/res_rc.py ./resources/res.qrc

# etc
uic main_tim.ui ./RWESharp/ui/uiscripts/mainui.py
uic special/aboutdialog.ui ./RWESharp/ui/uiscripts/about.py
uic special/explorer2.ui ./BaseMod/ui/explorer_ui.py
uic special/splash.ui ./RWESharp/ui/uiscripts/splash.py
uic special/Palette.ui ./BaseMod/themes/paletteui.py
uic settings/Preferences.ui ./BaseMod/themes/preferencesui.py

uic special/keydialog.ui ./RWESharp/ui/uiscripts/keydialog.py
uic special/PenPicker.ui ./RWESharp/ui/uiscripts/PenPicker.py

uic special/hotkeys.ui ./RWESharp/ui/uiscripts/hotkeys.py
uic special/settings.ui ./RWESharp/ui/uiscripts/settings.py
uic special/createcategory.ui ./BaseMod/ui/createcategory_ui.py
uic special/itemaction.ui ./BaseMod/ui/itemaction_ui.py

# geometry
uic editors/geometry.ui ./BaseMod/geo/ui/geometry_ui.py
uic views/geometry.ui ./BaseMod/geo/ui/geometry_vis_ui.py
uic settings/geo.ui ./BaseMod/geo/ui/geosettings_ui.py

# tiles
uic special/tilepin.ui ./BaseMod/tiles/ui/tilepin.py
uic editors/tiles.ui ./BaseMod/tiles/ui/tiles_ui.py
uic views/tiles.ui ./BaseMod/tiles/ui/tiles_vis_ui.py
uic settings/tiles.ui ./BaseMod/tiles/ui/tilesettings_ui.py

# props
uic editors/props.ui ./BaseMod/props/ui/props_ui.py
uic views/props.ui ./BaseMod/props/ui/props_vis_ui.py

# cameras
uic editors/cameras.ui ./BaseMod/camera/ui/cameras_ui.py
uic views/camera.ui ./BaseMod/camera/ui/camera_vis_ui.py
uic settings/cameras.ui ./BaseMod/camera/ui/camerasettings_ui.py

# grid
uic views/grid.ui ./BaseMod/grid/grid_ui.py

# effects
uic editors/effects.ui ./BaseMod/effects/ui/effects_ui.py
uic special/effectdialog.ui ./BaseMod/effects/ui/effectsdialog.py
uic special/effectexplorer.ui ./BaseMod/effects/ui/effectexplorer_ui.py
uic views/effects.ui ./BaseMod/effects/ui/effectsview_ui.py

# light
uic editors/light.ui ./BaseMod/light/ui/light_ui.py
uic views/light.ui ./BaseMod/light/ui/light_vis_ui.py

# properties
uic editors/properties.ui ./BaseMod/properties/ui/properties_ui.py
