# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_tim.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QDockWidget, QGridLayout, QHBoxLayout,
    QLabel, QMainWindow, QMenu, QMenuBar,
    QPushButton, QScrollArea, QSizePolicy, QSpinBox,
    QStatusBar, QTabWidget, QVBoxLayout, QWidget)

from RWESharpWidgets import ViewDockWidget
import ui.res_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1351, 968)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(1, 400))
        icon = QIcon()
        icon.addFile(u":/icons/icon.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(u"")
        MainWindow.setTabShape(QTabWidget.TabShape.Rounded)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QMainWindow.DockOption.AllowTabbedDocks|QMainWindow.DockOption.AnimatedDocks|QMainWindow.DockOption.VerticalTabs)
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        icon1 = QIcon(QIcon.fromTheme(u"document-open"))
        self.actionOpen.setIcon(icon1)
        self.actionNew = QAction(MainWindow)
        self.actionNew.setObjectName(u"actionNew")
        icon2 = QIcon(QIcon.fromTheme(u"document-new"))
        self.actionNew.setIcon(icon2)
        self.actionClose = QAction(MainWindow)
        self.actionClose.setObjectName(u"actionClose")
        icon3 = QIcon(QIcon.fromTheme(u"application-exit"))
        self.actionClose.setIcon(icon3)
        self.actionClose.setMenuRole(QAction.MenuRole.QuitRole)
        self.actionlevel1 = QAction(MainWindow)
        self.actionlevel1.setObjectName(u"actionlevel1")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        icon4 = QIcon(QIcon.fromTheme(u"document-save"))
        self.actionSave.setIcon(icon4)
        self.actionSave_As = QAction(MainWindow)
        self.actionSave_As.setObjectName(u"actionSave_As")
        icon5 = QIcon(QIcon.fromTheme(u"document-save-as"))
        self.actionSave_As.setIcon(icon5)
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        icon6 = QIcon(QIcon.fromTheme(u"dialog-information"))
        self.actionAbout.setIcon(icon6)
        self.actionAbout.setMenuRole(QAction.MenuRole.AboutRole)
        self.actionAbout_Qt = QAction(MainWindow)
        self.actionAbout_Qt.setObjectName(u"actionAbout_Qt")
        self.actionAbout_Qt.setIcon(icon6)
        self.actionAbout_Qt.setMenuRole(QAction.MenuRole.AboutQtRole)
        self.actionPreferences = QAction(MainWindow)
        self.actionPreferences.setObjectName(u"actionPreferences")
        icon7 = QIcon(QIcon.fromTheme(u"document-properties"))
        self.actionPreferences.setIcon(icon7)
        self.actionPreferences.setMenuRole(QAction.MenuRole.PreferencesRole)
        self.actionRender = QAction(MainWindow)
        self.actionRender.setObjectName(u"actionRender")
        self.actionHotkeys = QAction(MainWindow)
        self.actionHotkeys.setObjectName(u"actionHotkeys")
        icon8 = QIcon(QIcon.fromTheme(u"input-keyboard"))
        self.actionHotkeys.setIcon(icon8)
        self.actionDrizzleOpenExplorer = QAction(MainWindow)
        self.actionDrizzleOpenExplorer.setObjectName(u"actionDrizzleOpenExplorer")
        icon9 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.FolderOpen))
        self.actionDrizzleOpenExplorer.setIcon(icon9)
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName(u"actionUndo")
        icon10 = QIcon(QIcon.fromTheme(u"edit-undo"))
        self.actionUndo.setIcon(icon10)
        self.actionRedo = QAction(MainWindow)
        self.actionRedo.setObjectName(u"actionRedo")
        icon11 = QIcon(QIcon.fromTheme(u"edit-redo"))
        self.actionRedo.setIcon(icon11)
        self.actionEditors = QAction(MainWindow)
        self.actionEditors.setObjectName(u"actionEditors")
        self.actionEditors.setCheckable(True)
        self.actionView = QAction(MainWindow)
        self.actionView.setObjectName(u"actionView")
        self.actionView.setCheckable(True)
        self.actionPrefabs = QAction(MainWindow)
        self.actionPrefabs.setObjectName(u"actionPrefabs")
        self.actionPrefabs.setCheckable(True)
        self.actionZoom_In = QAction(MainWindow)
        self.actionZoom_In.setObjectName(u"actionZoom_In")
        self.actionZoom_Out = QAction(MainWindow)
        self.actionZoom_Out.setObjectName(u"actionZoom_Out")
        self.actionRender_All_Levels = QAction(MainWindow)
        self.actionRender_All_Levels.setObjectName(u"actionRender_All_Levels")
        self.actionLaunch_Drizzle = QAction(MainWindow)
        self.actionLaunch_Drizzle.setObjectName(u"actionLaunch_Drizzle")
        self.actionRWE_Github = QAction(MainWindow)
        self.actionRWE_Github.setObjectName(u"actionRWE_Github")
        icon12 = QIcon()
        icon12.addFile(u":/icons/github-mark-white.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionRWE_Github.setIcon(icon12)
        self.actionRWE_Issues = QAction(MainWindow)
        self.actionRWE_Issues.setObjectName(u"actionRWE_Issues")
        self.actionRWE_Issues.setIcon(icon12)
        self.actionOpen_Levels_Folder = QAction(MainWindow)
        self.actionOpen_Levels_Folder.setObjectName(u"actionOpen_Levels_Folder")
        self.actionOpen_Levels_Folder.setIcon(icon9)
        self.actionOpen_ShowLevelFile = QAction(MainWindow)
        self.actionOpen_ShowLevelFile.setObjectName(u"actionOpen_ShowLevelFile")
        self.actionOpen_ShowLevelFile.setIcon(icon9)
        self.actionNext_Layer = QAction(MainWindow)
        self.actionNext_Layer.setObjectName(u"actionNext_Layer")
        self.actionPrevious_Layer = QAction(MainWindow)
        self.actionPrevious_Layer.setObjectName(u"actionPrevious_Layer")
        self.actionReset_Viewport = QAction(MainWindow)
        self.actionReset_Viewport.setObjectName(u"actionReset_Viewport")
        icon13 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ViewRefresh))
        self.actionReset_Viewport.setIcon(icon13)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout_6 = QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setTabShape(QTabWidget.TabShape.Rounded)
        self.tabWidget.setElideMode(Qt.TextElideMode.ElideNone)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.level1 = QWidget()
        self.level1.setObjectName(u"level1")
        self.gridLayout_3 = QGridLayout(self.level1)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.tabWidget.addTab(self.level1, "")
        self.new = QWidget()
        self.new.setObjectName(u"new")
        self.gridLayout = QGridLayout(self.new)
        self.gridLayout.setObjectName(u"gridLayout")
        self.tabWidget.addTab(self.new, "")

        self.gridLayout_6.addWidget(self.tabWidget, 0, 1, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setEnabled(True)
        MainWindow.setStatusBar(self.statusbar)
        self.DockTools = ViewDockWidget(MainWindow)
        self.DockTools.setObjectName(u"DockTools")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(3)
        sizePolicy1.setHeightForWidth(self.DockTools.sizePolicy().hasHeightForWidth())
        self.DockTools.setSizePolicy(sizePolicy1)
        self.DockTools.setMinimumSize(QSize(238, 571))
        self.DockTools.setMaximumSize(QSize(524287, 524287))
        icon14 = QIcon()
        icon14.addFile(u":/icons/icon_small.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.DockTools.setWindowIcon(icon14)
        self.DockTools.setStyleSheet(u"")
        self.DockTools.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.DockTools.setFeatures(QDockWidget.DockWidgetFeature.DockWidgetClosable|QDockWidget.DockWidgetFeature.DockWidgetFloatable|QDockWidget.DockWidgetFeature.DockWidgetMovable)
        self.spacer = QWidget()
        self.spacer.setObjectName(u"spacer")
        self.gridLayout_2 = QGridLayout(self.spacer)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.ToolsTabs = QTabWidget(self.spacer)
        self.ToolsTabs.setObjectName(u"ToolsTabs")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Ignored)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.ToolsTabs.sizePolicy().hasHeightForWidth())
        self.ToolsTabs.setSizePolicy(sizePolicy2)
        self.ToolsTabs.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.ToolsTabs.setAutoFillBackground(False)
        self.ToolsTabs.setStyleSheet(u"")
        self.ToolsTabs.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))

        self.gridLayout_2.addWidget(self.ToolsTabs, 0, 1, 1, 1)

        self.DockTools.setWidget(self.spacer)
        MainWindow.addDockWidget(Qt.DockWidgetArea.LeftDockWidgetArea, self.DockTools)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1351, 27))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuRecent = QMenu(self.menuFile)
        self.menuRecent.setObjectName(u"menuRecent")
        icon15 = QIcon(QIcon.fromTheme(u"document-open-recent"))
        self.menuRecent.setIcon(icon15)
        self.menuSettings = QMenu(self.menubar)
        self.menuSettings.setObjectName(u"menuSettings")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menutools = QMenu(self.menubar)
        self.menutools.setObjectName(u"menutools")
        self.menuDrizzle = QMenu(self.menubar)
        self.menuDrizzle.setObjectName(u"menuDrizzle")
        self.menuMods = QMenu(self.menubar)
        self.menuMods.setObjectName(u"menuMods")
        self.menuConfigure = QMenu(self.menuMods)
        self.menuConfigure.setObjectName(u"menuConfigure")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        self.menuedit = QMenu(self.menubar)
        self.menuedit.setObjectName(u"menuedit")
        self.menuWindow = QMenu(self.menubar)
        self.menuWindow.setObjectName(u"menuWindow")
        self.menuEditors = QMenu(self.menubar)
        self.menuEditors.setObjectName(u"menuEditors")
        MainWindow.setMenuBar(self.menubar)
        self.DockView = ViewDockWidget(MainWindow)
        self.DockView.setObjectName(u"DockView")
        self.DockView.setEnabled(True)
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(1)
        sizePolicy3.setHeightForWidth(self.DockView.sizePolicy().hasHeightForWidth())
        self.DockView.setSizePolicy(sizePolicy3)
        self.DockView.setMinimumSize(QSize(161, 176))
        self.DockView.setMaximumSize(QSize(524287, 524287))
        self.DockView.setBaseSize(QSize(200, 300))
        self.DockView.setAcceptDrops(True)
        self.DockView.setWindowIcon(icon14)
        self.DockView.setFeatures(QDockWidget.DockWidgetFeature.DockWidgetClosable|QDockWidget.DockWidgetFeature.DockWidgetFloatable|QDockWidget.DockWidgetFeature.DockWidgetMovable)
        self.ViewDock = QWidget()
        self.ViewDock.setObjectName(u"ViewDock")
        self.verticalLayout_2 = QVBoxLayout(self.ViewDock)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.ViewTab = QTabWidget(self.ViewDock)
        self.ViewTab.setObjectName(u"ViewTab")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.ViewTab.sizePolicy().hasHeightForWidth())
        self.ViewTab.setSizePolicy(sizePolicy4)
        self.VQuick = QWidget()
        self.VQuick.setObjectName(u"VQuick")
        self.verticalLayout_8 = QVBoxLayout(self.VQuick)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.scrollArea_4 = QScrollArea(self.VQuick)
        self.scrollArea_4.setObjectName(u"scrollArea_4")
        sizePolicy4.setHeightForWidth(self.scrollArea_4.sizePolicy().hasHeightForWidth())
        self.scrollArea_4.setSizePolicy(sizePolicy4)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollAreaWidgetContents_4 = QWidget()
        self.scrollAreaWidgetContents_4.setObjectName(u"scrollAreaWidgetContents_4")
        self.scrollAreaWidgetContents_4.setGeometry(QRect(0, 0, 194, 163))
        self.verticalLayout = QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.label = QLabel(self.scrollAreaWidgetContents_4)
        self.label.setObjectName(u"label")

        self.horizontalLayout.addWidget(self.label)

        self.LayerChange = QSpinBox(self.scrollAreaWidgetContents_4)
        self.LayerChange.setObjectName(u"LayerChange")
        self.LayerChange.setWrapping(True)
        self.LayerChange.setMaximum(2)

        self.horizontalLayout.addWidget(self.LayerChange)


        self.verticalLayout.addLayout(self.horizontalLayout)

        self.QuickOverlay = QVBoxLayout()
        self.QuickOverlay.setObjectName(u"QuickOverlay")
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.NextLayer = QPushButton(self.scrollAreaWidgetContents_4)
        self.NextLayer.setObjectName(u"NextLayer")

        self.horizontalLayout_2.addWidget(self.NextLayer)

        self.PreviousLayer = QPushButton(self.scrollAreaWidgetContents_4)
        self.PreviousLayer.setObjectName(u"PreviousLayer")

        self.horizontalLayout_2.addWidget(self.PreviousLayer)


        self.QuickOverlay.addLayout(self.horizontalLayout_2)

        self.VQuickLabel = QLabel(self.scrollAreaWidgetContents_4)
        self.VQuickLabel.setObjectName(u"VQuickLabel")

        self.QuickOverlay.addWidget(self.VQuickLabel)


        self.verticalLayout.addLayout(self.QuickOverlay)

        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)

        self.verticalLayout_8.addWidget(self.scrollArea_4)

        self.ViewTab.addTab(self.VQuick, "")

        self.verticalLayout_2.addWidget(self.ViewTab)

        self.DockView.setWidget(self.ViewDock)
        MainWindow.addDockWidget(Qt.DockWidgetArea.LeftDockWidgetArea, self.DockView)
        self.DockPrefabs = ViewDockWidget(MainWindow)
        self.DockPrefabs.setObjectName(u"DockPrefabs")
        self.DockPrefabs.setFeatures(QDockWidget.DockWidgetFeature.DockWidgetClosable|QDockWidget.DockWidgetFeature.DockWidgetFloatable|QDockWidget.DockWidgetFeature.DockWidgetMovable)
        self.dockWidgetContents_2 = QWidget()
        self.dockWidgetContents_2.setObjectName(u"dockWidgetContents_2")
        self.label_14 = QLabel(self.dockWidgetContents_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 10, 131, 16))
        self.DockPrefabs.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.DockPrefabs)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuedit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menutools.menuAction())
        self.menubar.addAction(self.menuEditors.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuDrizzle.menuAction())
        self.menubar.addAction(self.menuMods.menuAction())
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.menuRecent.menuAction())
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen_Levels_Folder)
        self.menuFile.addAction(self.actionOpen_ShowLevelFile)
        self.menuSettings.addAction(self.actionPreferences)
        self.menuSettings.addAction(self.actionHotkeys)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionAbout_Qt)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionRWE_Github)
        self.menuHelp.addAction(self.actionRWE_Issues)
        self.menuDrizzle.addAction(self.actionRender)
        self.menuDrizzle.addAction(self.actionRender_All_Levels)
        self.menuDrizzle.addAction(self.actionDrizzleOpenExplorer)
        self.menuDrizzle.addAction(self.actionLaunch_Drizzle)
        self.menuMods.addAction(self.menuConfigure.menuAction())
        self.menuView.addAction(self.actionReset_Viewport)
        self.menuedit.addAction(self.actionUndo)
        self.menuedit.addAction(self.actionRedo)
        self.menuedit.addSeparator()
        self.menuedit.addAction(self.actionZoom_In)
        self.menuedit.addAction(self.actionZoom_Out)
        self.menuedit.addSeparator()
        self.menuedit.addAction(self.actionNext_Layer)
        self.menuedit.addAction(self.actionPrevious_Layer)
        self.menuWindow.addAction(self.actionEditors)
        self.menuWindow.addAction(self.actionView)
        self.menuWindow.addAction(self.actionPrefabs)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)
        self.ToolsTabs.setCurrentIndex(-1)
        self.ViewTab.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"RWE#", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.actionNew.setText(QCoreApplication.translate("MainWindow", u"New", None))
#if QT_CONFIG(tooltip)
        self.actionNew.setToolTip(QCoreApplication.translate("MainWindow", u"New level", None))
#endif // QT_CONFIG(tooltip)
        self.actionClose.setText(QCoreApplication.translate("MainWindow", u"Close", None))
        self.actionlevel1.setText(QCoreApplication.translate("MainWindow", u"level1", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
#if QT_CONFIG(tooltip)
        self.actionSave.setToolTip(QCoreApplication.translate("MainWindow", u"Save the level", None))
#endif // QT_CONFIG(tooltip)
        self.actionSave_As.setText(QCoreApplication.translate("MainWindow", u"Save As...", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionAbout_Qt.setText(QCoreApplication.translate("MainWindow", u"About Qt", None))
        self.actionPreferences.setText(QCoreApplication.translate("MainWindow", u"Preferences...", None))
        self.actionRender.setText(QCoreApplication.translate("MainWindow", u"Render", None))
        self.actionHotkeys.setText(QCoreApplication.translate("MainWindow", u"Hotkeys...", None))
        self.actionDrizzleOpenExplorer.setText(QCoreApplication.translate("MainWindow", u"Open Drizzle in Explorer", None))
        self.actionUndo.setText(QCoreApplication.translate("MainWindow", u"Undo", None))
        self.actionRedo.setText(QCoreApplication.translate("MainWindow", u"Redo", None))
        self.actionEditors.setText(QCoreApplication.translate("MainWindow", u"Editors", None))
        self.actionView.setText(QCoreApplication.translate("MainWindow", u"View", None))
        self.actionPrefabs.setText(QCoreApplication.translate("MainWindow", u"Prefabs", None))
        self.actionZoom_In.setText(QCoreApplication.translate("MainWindow", u"Zoom In", None))
        self.actionZoom_Out.setText(QCoreApplication.translate("MainWindow", u"Zoom Out", None))
        self.actionRender_All_Levels.setText(QCoreApplication.translate("MainWindow", u"Render All Levels", None))
        self.actionLaunch_Drizzle.setText(QCoreApplication.translate("MainWindow", u"Launch Drizzle", None))
        self.actionRWE_Github.setText(QCoreApplication.translate("MainWindow", u"RWE# Github", None))
        self.actionRWE_Issues.setText(QCoreApplication.translate("MainWindow", u"RWE# Issues", None))
        self.actionOpen_Levels_Folder.setText(QCoreApplication.translate("MainWindow", u"Open Levels Folder", None))
        self.actionOpen_ShowLevelFile.setText(QCoreApplication.translate("MainWindow", u"Show Level File", None))
        self.actionNext_Layer.setText(QCoreApplication.translate("MainWindow", u"Next Layer", None))
        self.actionPrevious_Layer.setText(QCoreApplication.translate("MainWindow", u"Previous Layer", None))
        self.actionReset_Viewport.setText(QCoreApplication.translate("MainWindow", u"Reset Viewport", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.level1), QCoreApplication.translate("MainWindow", u"Level", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.new), QCoreApplication.translate("MainWindow", u"New level", None))
        self.DockTools.setWindowTitle(QCoreApplication.translate("MainWindow", u"Editors", None))
#if QT_CONFIG(tooltip)
        self.ToolsTabs.setToolTip(QCoreApplication.translate("MainWindow", u"Toggle view for ceirtain objects", None))
#endif // QT_CONFIG(tooltip)
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuRecent.setTitle(QCoreApplication.translate("MainWindow", u"Recent...", None))
        self.menuSettings.setTitle(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menutools.setTitle(QCoreApplication.translate("MainWindow", u"Tools", None))
        self.menuDrizzle.setTitle(QCoreApplication.translate("MainWindow", u"Drizzle", None))
        self.menuMods.setTitle(QCoreApplication.translate("MainWindow", u"Mods", None))
        self.menuConfigure.setTitle(QCoreApplication.translate("MainWindow", u"Configure", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuedit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuWindow.setTitle(QCoreApplication.translate("MainWindow", u"Window", None))
        self.menuEditors.setTitle(QCoreApplication.translate("MainWindow", u"Editors", None))
        self.DockView.setWindowTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Layer:", None))
        self.NextLayer.setText(QCoreApplication.translate("MainWindow", u"Next", None))
        self.PreviousLayer.setText(QCoreApplication.translate("MainWindow", u"Previous", None))
        self.VQuickLabel.setText(QCoreApplication.translate("MainWindow", u"Show:", None))
        self.ViewTab.setTabText(self.ViewTab.indexOf(self.VQuick), QCoreApplication.translate("MainWindow", u"Quick", None))
        self.DockPrefabs.setWindowTitle(QCoreApplication.translate("MainWindow", u"Prefabs", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Prefabs idk", None))
    # retranslateUi

