# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_tim.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QDockWidget, QGridLayout, QLabel,
    QMainWindow, QMenu, QMenuBar, QScrollArea,
    QSizePolicy, QStatusBar, QTabWidget, QVBoxLayout,
    QWidget)

from RWESharpWidgets import ViewPort
import ui.res_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1351, 968)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(1, 400))
        icon = QIcon()
        icon.addFile(u":/icons/icon_small.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(u"")
        MainWindow.setTabShape(QTabWidget.TabShape.Rounded)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QMainWindow.DockOption.AllowTabbedDocks|QMainWindow.DockOption.AnimatedDocks|QMainWindow.DockOption.VerticalTabs)
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        icon1 = QIcon(QIcon.fromTheme(u"document-open"))
        self.actionOpen.setIcon(icon1)
        self.actionNew = QAction(MainWindow)
        self.actionNew.setObjectName(u"actionNew")
        icon2 = QIcon(QIcon.fromTheme(u"document-new"))
        self.actionNew.setIcon(icon2)
        self.actionClose = QAction(MainWindow)
        self.actionClose.setObjectName(u"actionClose")
        icon3 = QIcon(QIcon.fromTheme(u"application-exit"))
        self.actionClose.setIcon(icon3)
        self.actionClose.setMenuRole(QAction.MenuRole.QuitRole)
        self.actionlevel1 = QAction(MainWindow)
        self.actionlevel1.setObjectName(u"actionlevel1")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        icon4 = QIcon(QIcon.fromTheme(u"document-save"))
        self.actionSave.setIcon(icon4)
        self.actionSave_As = QAction(MainWindow)
        self.actionSave_As.setObjectName(u"actionSave_As")
        icon5 = QIcon(QIcon.fromTheme(u"document-save-as"))
        self.actionSave_As.setIcon(icon5)
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        icon6 = QIcon(QIcon.fromTheme(u"dialog-information"))
        self.actionAbout.setIcon(icon6)
        self.actionAbout.setMenuRole(QAction.MenuRole.AboutRole)
        self.actionWiki_window = QAction(MainWindow)
        self.actionWiki_window.setObjectName(u"actionWiki_window")
        self.actionWiki_window.setCheckable(True)
        icon7 = QIcon(QIcon.fromTheme(u"dialog-question"))
        self.actionWiki_window.setIcon(icon7)
        self.actionAbout_Qt = QAction(MainWindow)
        self.actionAbout_Qt.setObjectName(u"actionAbout_Qt")
        self.actionAbout_Qt.setIcon(icon6)
        self.actionAbout_Qt.setMenuRole(QAction.MenuRole.AboutQtRole)
        self.actionPreferences = QAction(MainWindow)
        self.actionPreferences.setObjectName(u"actionPreferences")
        icon8 = QIcon(QIcon.fromTheme(u"document-properties"))
        self.actionPreferences.setIcon(icon8)
        self.actionPreferences.setMenuRole(QAction.MenuRole.PreferencesRole)
        self.actionRender = QAction(MainWindow)
        self.actionRender.setObjectName(u"actionRender")
        self.actionexplode_leditor = QAction(MainWindow)
        self.actionexplode_leditor.setObjectName(u"actionexplode_leditor")
        self.actionLediting_help = QAction(MainWindow)
        self.actionLediting_help.setObjectName(u"actionLediting_help")
        self.actionRender_2 = QAction(MainWindow)
        self.actionRender_2.setObjectName(u"actionRender_2")
        self.actionHotkeys = QAction(MainWindow)
        self.actionHotkeys.setObjectName(u"actionHotkeys")
        icon9 = QIcon(QIcon.fromTheme(u"input-keyboard"))
        self.actionHotkeys.setIcon(icon9)
        self.actionOpen_2 = QAction(MainWindow)
        self.actionOpen_2.setObjectName(u"actionOpen_2")
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName(u"actionUndo")
        icon10 = QIcon(QIcon.fromTheme(u"edit-undo"))
        self.actionUndo.setIcon(icon10)
        self.actionRedo = QAction(MainWindow)
        self.actionRedo.setObjectName(u"actionRedo")
        icon11 = QIcon(QIcon.fromTheme(u"edit-redo"))
        self.actionRedo.setIcon(icon11)
        self.actionModding_Api = QAction(MainWindow)
        self.actionModding_Api.setObjectName(u"actionModding_Api")
        self.actionInteractive_Map = QAction(MainWindow)
        self.actionInteractive_Map.setObjectName(u"actionInteractive_Map")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout_6 = QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.viewPort = ViewPort(self.centralwidget)
        self.viewPort.setObjectName(u"viewPort")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy1.setHorizontalStretch(2)
        sizePolicy1.setVerticalStretch(2)
        sizePolicy1.setHeightForWidth(self.viewPort.sizePolicy().hasHeightForWidth())
        self.viewPort.setSizePolicy(sizePolicy1)
        self.viewPort.setMouseTracking(True)
        self.viewPort.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))

        self.gridLayout_6.addWidget(self.viewPort, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setEnabled(True)
        MainWindow.setStatusBar(self.statusbar)
        self.DockTools = QDockWidget(MainWindow)
        self.DockTools.setObjectName(u"DockTools")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(3)
        sizePolicy2.setHeightForWidth(self.DockTools.sizePolicy().hasHeightForWidth())
        self.DockTools.setSizePolicy(sizePolicy2)
        self.DockTools.setMinimumSize(QSize(238, 571))
        self.DockTools.setMaximumSize(QSize(524287, 524287))
        self.DockTools.setWindowIcon(icon)
        self.DockTools.setStyleSheet(u"")
        self.DockTools.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.DockTools.setFeatures(QDockWidget.DockWidgetFeature.DockWidgetFloatable|QDockWidget.DockWidgetFeature.DockWidgetMovable)
        self.spacer = QWidget()
        self.spacer.setObjectName(u"spacer")
        self.gridLayout_2 = QGridLayout(self.spacer)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.ToolsTabs = QTabWidget(self.spacer)
        self.ToolsTabs.setObjectName(u"ToolsTabs")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Ignored)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.ToolsTabs.sizePolicy().hasHeightForWidth())
        self.ToolsTabs.setSizePolicy(sizePolicy3)
        self.ToolsTabs.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.ToolsTabs.setAutoFillBackground(False)
        self.ToolsTabs.setStyleSheet(u"")
        self.ToolsTabs.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))

        self.gridLayout_2.addWidget(self.ToolsTabs, 0, 1, 1, 1)

        self.DockTools.setWidget(self.spacer)
        MainWindow.addDockWidget(Qt.DockWidgetArea.LeftDockWidgetArea, self.DockTools)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1351, 33))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuRecent = QMenu(self.menuFile)
        self.menuRecent.setObjectName(u"menuRecent")
        icon12 = QIcon(QIcon.fromTheme(u"document-open-recent"))
        self.menuRecent.setIcon(icon12)
        self.menuSettings = QMenu(self.menubar)
        self.menuSettings.setObjectName(u"menuSettings")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menutools = QMenu(self.menubar)
        self.menutools.setObjectName(u"menutools")
        self.menuDrizzle = QMenu(self.menubar)
        self.menuDrizzle.setObjectName(u"menuDrizzle")
        self.menuMods = QMenu(self.menubar)
        self.menuMods.setObjectName(u"menuMods")
        self.menuConfigure = QMenu(self.menuMods)
        self.menuConfigure.setObjectName(u"menuConfigure")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        self.menuedit = QMenu(self.menubar)
        self.menuedit.setObjectName(u"menuedit")
        MainWindow.setMenuBar(self.menubar)
        self.DockView = QDockWidget(MainWindow)
        self.DockView.setObjectName(u"DockView")
        self.DockView.setEnabled(True)
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(1)
        sizePolicy4.setHeightForWidth(self.DockView.sizePolicy().hasHeightForWidth())
        self.DockView.setSizePolicy(sizePolicy4)
        self.DockView.setMinimumSize(QSize(145, 161))
        self.DockView.setMaximumSize(QSize(524287, 524287))
        self.DockView.setBaseSize(QSize(200, 300))
        self.DockView.setAcceptDrops(True)
        self.DockView.setWindowIcon(icon)
        self.DockView.setFeatures(QDockWidget.DockWidgetFeature.DockWidgetFloatable|QDockWidget.DockWidgetFeature.DockWidgetMovable)
        self.ViewDock = QWidget()
        self.ViewDock.setObjectName(u"ViewDock")
        self.verticalLayout_2 = QVBoxLayout(self.ViewDock)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.ViewTab = QTabWidget(self.ViewDock)
        self.ViewTab.setObjectName(u"ViewTab")
        sizePolicy5 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.ViewTab.sizePolicy().hasHeightForWidth())
        self.ViewTab.setSizePolicy(sizePolicy5)
        self.VQuick = QWidget()
        self.VQuick.setObjectName(u"VQuick")
        self.verticalLayout_8 = QVBoxLayout(self.VQuick)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.scrollArea_4 = QScrollArea(self.VQuick)
        self.scrollArea_4.setObjectName(u"scrollArea_4")
        sizePolicy5.setHeightForWidth(self.scrollArea_4.sizePolicy().hasHeightForWidth())
        self.scrollArea_4.setSizePolicy(sizePolicy5)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollAreaWidgetContents_4 = QWidget()
        self.scrollAreaWidgetContents_4.setObjectName(u"scrollAreaWidgetContents_4")
        self.scrollAreaWidgetContents_4.setGeometry(QRect(0, 0, 194, 109))
        self.verticalLayout = QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.QuickOverlay = QVBoxLayout()
        self.QuickOverlay.setObjectName(u"QuickOverlay")
        self.VQuickLabel = QLabel(self.scrollAreaWidgetContents_4)
        self.VQuickLabel.setObjectName(u"VQuickLabel")

        self.QuickOverlay.addWidget(self.VQuickLabel)


        self.verticalLayout.addLayout(self.QuickOverlay)

        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)

        self.verticalLayout_8.addWidget(self.scrollArea_4)

        self.ViewTab.addTab(self.VQuick, "")

        self.verticalLayout_2.addWidget(self.ViewTab)

        self.DockView.setWidget(self.ViewDock)
        MainWindow.addDockWidget(Qt.DockWidgetArea.LeftDockWidgetArea, self.DockView)
        self.dockWidget_2 = QDockWidget(MainWindow)
        self.dockWidget_2.setObjectName(u"dockWidget_2")
        self.dockWidget_2.setFeatures(QDockWidget.DockWidgetFeature.DockWidgetFloatable|QDockWidget.DockWidgetFeature.DockWidgetMovable)
        self.dockWidgetContents_2 = QWidget()
        self.dockWidgetContents_2.setObjectName(u"dockWidgetContents_2")
        self.label_14 = QLabel(self.dockWidgetContents_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 10, 131, 16))
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.dockWidget_2)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuedit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menutools.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuDrizzle.menuAction())
        self.menubar.addAction(self.menuMods.menuAction())
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.menuRecent.menuAction())
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuSettings.addAction(self.actionPreferences)
        self.menuSettings.addAction(self.actionHotkeys)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionAbout_Qt)
        self.menuHelp.addAction(self.actionWiki_window)
        self.menuHelp.addAction(self.actionLediting_help)
        self.menuHelp.addAction(self.actionModding_Api)
        self.menuHelp.addAction(self.actionInteractive_Map)
        self.menuDrizzle.addAction(self.actionRender_2)
        self.menuDrizzle.addAction(self.actionOpen_2)
        self.menuMods.addAction(self.menuConfigure.menuAction())
        self.menuedit.addAction(self.actionUndo)
        self.menuedit.addAction(self.actionRedo)

        self.retranslateUi(MainWindow)

        self.ToolsTabs.setCurrentIndex(-1)
        self.ViewTab.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"RWE#", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.actionNew.setText(QCoreApplication.translate("MainWindow", u"New", None))
#if QT_CONFIG(tooltip)
        self.actionNew.setToolTip(QCoreApplication.translate("MainWindow", u"New level", None))
#endif // QT_CONFIG(tooltip)
        self.actionClose.setText(QCoreApplication.translate("MainWindow", u"Close", None))
        self.actionlevel1.setText(QCoreApplication.translate("MainWindow", u"level1", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
#if QT_CONFIG(tooltip)
        self.actionSave.setToolTip(QCoreApplication.translate("MainWindow", u"Save the level", None))
#endif // QT_CONFIG(tooltip)
        self.actionSave_As.setText(QCoreApplication.translate("MainWindow", u"Save As...", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionWiki_window.setText(QCoreApplication.translate("MainWindow", u"Wiki", None))
        self.actionAbout_Qt.setText(QCoreApplication.translate("MainWindow", u"About Qt", None))
        self.actionPreferences.setText(QCoreApplication.translate("MainWindow", u"Preferences...", None))
        self.actionRender.setText(QCoreApplication.translate("MainWindow", u"Render", None))
        self.actionexplode_leditor.setText(QCoreApplication.translate("MainWindow", u"explode leditor", None))
        self.actionLediting_help.setText(QCoreApplication.translate("MainWindow", u"Lediting help", None))
        self.actionRender_2.setText(QCoreApplication.translate("MainWindow", u"Render", None))
        self.actionHotkeys.setText(QCoreApplication.translate("MainWindow", u"Hotkeys", None))
        self.actionOpen_2.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.actionUndo.setText(QCoreApplication.translate("MainWindow", u"Undo", None))
        self.actionRedo.setText(QCoreApplication.translate("MainWindow", u"Redo", None))
        self.actionModding_Api.setText(QCoreApplication.translate("MainWindow", u"Modding Api", None))
        self.actionInteractive_Map.setText(QCoreApplication.translate("MainWindow", u"Interactive Map", None))
        self.DockTools.setWindowTitle(QCoreApplication.translate("MainWindow", u"Editors", None))
#if QT_CONFIG(tooltip)
        self.ToolsTabs.setToolTip(QCoreApplication.translate("MainWindow", u"Toggle view for ceirtain objects", None))
#endif // QT_CONFIG(tooltip)
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuRecent.setTitle(QCoreApplication.translate("MainWindow", u"Recent...", None))
        self.menuSettings.setTitle(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menutools.setTitle(QCoreApplication.translate("MainWindow", u"Tools", None))
        self.menuDrizzle.setTitle(QCoreApplication.translate("MainWindow", u"Drizzle", None))
        self.menuMods.setTitle(QCoreApplication.translate("MainWindow", u"Mods", None))
        self.menuConfigure.setTitle(QCoreApplication.translate("MainWindow", u"Configure", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuedit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.DockView.setWindowTitle(QCoreApplication.translate("MainWindow", u"VIew", None))
        self.VQuickLabel.setText(QCoreApplication.translate("MainWindow", u"Show:", None))
        self.ViewTab.setTabText(self.ViewTab.indexOf(self.VQuick), QCoreApplication.translate("MainWindow", u"Quick", None))
        self.dockWidget_2.setWindowTitle(QCoreApplication.translate("MainWindow", u"Prefabs", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Prefabs idk", None))
    # retranslateUi

