# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QDockWidget, QFrame,
    QGridLayout, QHeaderView, QLabel, QLayout,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QSizePolicy, QSplitter, QStatusBar, QTabWidget,
    QTableView, QVBoxLayout, QWidget)

from RWESharpWidgets import ViewPort
import ui.res_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1079, 507)
        icon = QIcon()
        icon.addFile(u":/icons/icon_small.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        icon1 = QIcon(QIcon.fromTheme(u"document-open"))
        self.actionOpen.setIcon(icon1)
        self.actionNew = QAction(MainWindow)
        self.actionNew.setObjectName(u"actionNew")
        icon2 = QIcon(QIcon.fromTheme(u"document-new"))
        self.actionNew.setIcon(icon2)
        self.actionClose = QAction(MainWindow)
        self.actionClose.setObjectName(u"actionClose")
        icon3 = QIcon(QIcon.fromTheme(u"application-exit"))
        self.actionClose.setIcon(icon3)
        self.actionClose.setMenuRole(QAction.MenuRole.QuitRole)
        self.actionlevel1 = QAction(MainWindow)
        self.actionlevel1.setObjectName(u"actionlevel1")
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName(u"actionUndo")
        icon4 = QIcon(QIcon.fromTheme(u"edit-undo"))
        self.actionUndo.setIcon(icon4)
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        icon5 = QIcon(QIcon.fromTheme(u"document-save"))
        self.actionSave.setIcon(icon5)
        self.actionSave_As = QAction(MainWindow)
        self.actionSave_As.setObjectName(u"actionSave_As")
        icon6 = QIcon(QIcon.fromTheme(u"document-save-as"))
        self.actionSave_As.setIcon(icon6)
        self.actionRedo = QAction(MainWindow)
        self.actionRedo.setObjectName(u"actionRedo")
        icon7 = QIcon(QIcon.fromTheme(u"edit-redo"))
        self.actionRedo.setIcon(icon7)
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        icon8 = QIcon(QIcon.fromTheme(u"help-about"))
        self.actionAbout.setIcon(icon8)
        self.actionAbout.setMenuRole(QAction.MenuRole.AboutRole)
        self.actionWiki_window = QAction(MainWindow)
        self.actionWiki_window.setObjectName(u"actionWiki_window")
        self.actionWiki_window.setCheckable(True)
        self.actionAbout_Qt = QAction(MainWindow)
        self.actionAbout_Qt.setObjectName(u"actionAbout_Qt")
        self.actionAbout_Qt.setIcon(icon8)
        self.actionAbout_Qt.setMenuRole(QAction.MenuRole.AboutQtRole)
        self.actionRender = QAction(MainWindow)
        self.actionRender.setObjectName(u"actionRender")
        self.actionPreferences = QAction(MainWindow)
        self.actionPreferences.setObjectName(u"actionPreferences")
        icon9 = QIcon(QIcon.fromTheme(u"document-properties"))
        self.actionPreferences.setIcon(icon9)
        self.actionPreferences.setMenuRole(QAction.MenuRole.PreferencesRole)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout_4 = QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.viewPort = ViewPort(self.centralwidget)
        self.viewPort.setObjectName(u"viewPort")
        self.viewPort.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))

        self.gridLayout_4.addWidget(self.viewPort, 1, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1079, 33))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuRecent = QMenu(self.menuFile)
        self.menuRecent.setObjectName(u"menuRecent")
        icon10 = QIcon(QIcon.fromTheme(u"document-open-recent"))
        self.menuRecent.setIcon(icon10)
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuWindow = QMenu(self.menubar)
        self.menuWindow.setObjectName(u"menuWindow")
        self.menuSettings = QMenu(self.menubar)
        self.menuSettings.setObjectName(u"menuSettings")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menu_3 = QMenu(self.menubar)
        self.menu_3.setObjectName(u"menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockmode = QDockWidget(MainWindow)
        self.dockmode.setObjectName(u"dockmode")
        self.dockmode.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.spacer = QWidget()
        self.spacer.setObjectName(u"spacer")
        self.gridLayout_2 = QGridLayout(self.spacer)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.tabWidget = QTabWidget(self.spacer)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.geo = QWidget()
        self.geo.setObjectName(u"geo")
        self.gridLayout_3 = QGridLayout(self.geo)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.geoSplitter = QSplitter(self.geo)
        self.geoSplitter.setObjectName(u"geoSplitter")
        self.geoSplitter.setOrientation(Qt.Orientation.Vertical)
        self.frame = QFrame(self.geoSplitter)
        self.frame.setObjectName(u"frame")
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout = QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.apply_to_text = QLabel(self.frame)
        self.apply_to_text.setObjectName(u"apply_to_text")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apply_to_text.sizePolicy().hasHeightForWidth())
        self.apply_to_text.setSizePolicy(sizePolicy)

        self.verticalLayout.addWidget(self.apply_to_text)

        self.geol1 = QCheckBox(self.frame)
        self.geol1.setObjectName(u"geol1")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(3)
        sizePolicy1.setHeightForWidth(self.geol1.sizePolicy().hasHeightForWidth())
        self.geol1.setSizePolicy(sizePolicy1)

        self.verticalLayout.addWidget(self.geol1)

        self.geol2 = QCheckBox(self.frame)
        self.geol2.setObjectName(u"geol2")
        sizePolicy1.setHeightForWidth(self.geol2.sizePolicy().hasHeightForWidth())
        self.geol2.setSizePolicy(sizePolicy1)

        self.verticalLayout.addWidget(self.geol2)

        self.geol3 = QCheckBox(self.frame)
        self.geol3.setObjectName(u"geol3")
        sizePolicy1.setHeightForWidth(self.geol3.sizePolicy().hasHeightForWidth())
        self.geol3.setSizePolicy(sizePolicy1)

        self.verticalLayout.addWidget(self.geol3)

        self.geoSplitter.addWidget(self.frame)
        self.frame_2 = QFrame(self.geoSplitter)
        self.frame_2.setObjectName(u"frame_2")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy2)
        self.frame_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_2 = QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setSizeConstraint(QLayout.SizeConstraint.SetMinimumSize)
        self.label_2 = QLabel(self.frame_2)
        self.label_2.setObjectName(u"label_2")
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)

        self.verticalLayout_2.addWidget(self.label_2)

        self.geoItems = QGridLayout()
        self.geoItems.setObjectName(u"geoItems")
        self.geoItems.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.geoSpear = QPushButton(self.frame_2)
        self.geoSpear.setObjectName(u"geoSpear")
        sizePolicy2.setHeightForWidth(self.geoSpear.sizePolicy().hasHeightForWidth())
        self.geoSpear.setSizePolicy(sizePolicy2)
        self.geoSpear.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))

        self.geoItems.addWidget(self.geoSpear, 6, 0, 1, 1)

        self.geoFloor = QPushButton(self.frame_2)
        self.geoFloor.setObjectName(u"geoFloor")
        sizePolicy2.setHeightForWidth(self.geoFloor.sizePolicy().hasHeightForWidth())
        self.geoFloor.setSizePolicy(sizePolicy2)
        self.geoFloor.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.geoFloor.setAutoRepeat(False)

        self.geoItems.addWidget(self.geoFloor, 3, 0, 1, 1)

        self.geoWall = QPushButton(self.frame_2)
        self.geoWall.setObjectName(u"geoWall")
        sizePolicy2.setHeightForWidth(self.geoWall.sizePolicy().hasHeightForWidth())
        self.geoWall.setSizePolicy(sizePolicy2)
        self.geoWall.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.geoWall.setIconSize(QSize(16, 16))
        self.geoWall.setCheckable(False)

        self.geoItems.addWidget(self.geoWall, 2, 0, 1, 1)

        self.geoHive = QPushButton(self.frame_2)
        self.geoHive.setObjectName(u"geoHive")
        sizePolicy2.setHeightForWidth(self.geoHive.sizePolicy().hasHeightForWidth())
        self.geoHive.setSizePolicy(sizePolicy2)
        self.geoHive.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))

        self.geoItems.addWidget(self.geoHive, 7, 0, 1, 1)

        self.geoGlass = QPushButton(self.frame_2)
        self.geoGlass.setObjectName(u"geoGlass")
        sizePolicy2.setHeightForWidth(self.geoGlass.sizePolicy().hasHeightForWidth())
        self.geoGlass.setSizePolicy(sizePolicy2)
        self.geoGlass.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))

        self.geoItems.addWidget(self.geoGlass, 4, 0, 1, 1)

        self.geoCrack = QPushButton(self.frame_2)
        self.geoCrack.setObjectName(u"geoCrack")
        sizePolicy2.setHeightForWidth(self.geoCrack.sizePolicy().hasHeightForWidth())
        self.geoCrack.setSizePolicy(sizePolicy2)
        self.geoCrack.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))

        self.geoItems.addWidget(self.geoCrack, 5, 1, 1, 1)

        self.geoForbidChains = QPushButton(self.frame_2)
        self.geoForbidChains.setObjectName(u"geoForbidChains")
        sizePolicy2.setHeightForWidth(self.geoForbidChains.sizePolicy().hasHeightForWidth())
        self.geoForbidChains.setSizePolicy(sizePolicy2)
        self.geoForbidChains.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))

        self.geoItems.addWidget(self.geoForbidChains, 7, 1, 1, 1)

        self.geoBeam = QPushButton(self.frame_2)
        self.geoBeam.setObjectName(u"geoBeam")
        sizePolicy2.setHeightForWidth(self.geoBeam.sizePolicy().hasHeightForWidth())
        self.geoBeam.setSizePolicy(sizePolicy2)
        self.geoBeam.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))

        self.geoItems.addWidget(self.geoBeam, 5, 0, 1, 1)

        self.geoAir = QPushButton(self.frame_2)
        self.geoAir.setObjectName(u"geoAir")
        sizePolicy2.setHeightForWidth(self.geoAir.sizePolicy().hasHeightForWidth())
        self.geoAir.setSizePolicy(sizePolicy2)
        self.geoAir.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))

        self.geoItems.addWidget(self.geoAir, 2, 1, 1, 1)

        self.geoRock = QPushButton(self.frame_2)
        self.geoRock.setObjectName(u"geoRock")
        sizePolicy2.setHeightForWidth(self.geoRock.sizePolicy().hasHeightForWidth())
        self.geoRock.setSizePolicy(sizePolicy2)
        self.geoRock.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))

        self.geoItems.addWidget(self.geoRock, 6, 1, 1, 1)

        self.geoSlope = QPushButton(self.frame_2)
        self.geoSlope.setObjectName(u"geoSlope")
        sizePolicy2.setHeightForWidth(self.geoSlope.sizePolicy().hasHeightForWidth())
        self.geoSlope.setSizePolicy(sizePolicy2)
        self.geoSlope.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))

        self.geoItems.addWidget(self.geoSlope, 3, 1, 1, 1)


        self.verticalLayout_2.addLayout(self.geoItems)

        self.geoSplitter.addWidget(self.frame_2)

        self.gridLayout_3.addWidget(self.geoSplitter, 2, 0, 1, 1)

        self.tabWidget.addTab(self.geo, "")
        self.tiles = QWidget()
        self.tiles.setObjectName(u"tiles")
        self.gridLayout = QGridLayout(self.tiles)
        self.gridLayout.setObjectName(u"gridLayout")
        self.splitter = QSplitter(self.tiles)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Orientation.Vertical)
        self.tableView = QTableView(self.splitter)
        self.tableView.setObjectName(u"tableView")
        self.splitter.addWidget(self.tableView)

        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)

        self.tabWidget.addTab(self.tiles, "")

        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.dockmode.setWidget(self.spacer)
        MainWindow.addDockWidget(Qt.DockWidgetArea.LeftDockWidgetArea, self.dockmode)
        QWidget.setTabOrder(self.tabWidget, self.tableView)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.menuRecent.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionRender)
        self.menuSettings.addAction(self.actionPreferences)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionAbout_Qt)
        self.menuHelp.addAction(self.actionWiki_window)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"RWE#", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
#if QT_CONFIG(shortcut)
        self.actionOpen.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionNew.setText(QCoreApplication.translate("MainWindow", u"New", None))
#if QT_CONFIG(tooltip)
        self.actionNew.setToolTip(QCoreApplication.translate("MainWindow", u"New level", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionNew.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionClose.setText(QCoreApplication.translate("MainWindow", u"Close", None))
        self.actionlevel1.setText(QCoreApplication.translate("MainWindow", u"level1", None))
        self.actionUndo.setText(QCoreApplication.translate("MainWindow", u"Undo", None))
#if QT_CONFIG(shortcut)
        self.actionUndo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
#if QT_CONFIG(tooltip)
        self.actionSave.setToolTip(QCoreApplication.translate("MainWindow", u"Save the level", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionSave.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave_As.setText(QCoreApplication.translate("MainWindow", u"Save As...", None))
#if QT_CONFIG(shortcut)
        self.actionSave_As.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionRedo.setText(QCoreApplication.translate("MainWindow", u"Redo", None))
#if QT_CONFIG(shortcut)
        self.actionRedo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+U, Ctrl+Shift+Z", None))
#endif // QT_CONFIG(shortcut)
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionWiki_window.setText(QCoreApplication.translate("MainWindow", u"Wiki window", None))
        self.actionAbout_Qt.setText(QCoreApplication.translate("MainWindow", u"About Qt", None))
        self.actionRender.setText(QCoreApplication.translate("MainWindow", u"Render", None))
#if QT_CONFIG(shortcut)
        self.actionRender.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+R", None))
#endif // QT_CONFIG(shortcut)
        self.actionPreferences.setText(QCoreApplication.translate("MainWindow", u"Preferences", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuRecent.setTitle(QCoreApplication.translate("MainWindow", u"Recent...", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuWindow.setTitle(QCoreApplication.translate("MainWindow", u"Window", None))
        self.menuSettings.setTitle(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menu_3.setTitle(QCoreApplication.translate("MainWindow", u":3", None))
        self.apply_to_text.setText(QCoreApplication.translate("MainWindow", u"Apply to:", None))
        self.geol1.setText(QCoreApplication.translate("MainWindow", u"Layer 1", None))
        self.geol2.setText(QCoreApplication.translate("MainWindow", u"Layer 2", None))
        self.geol3.setText(QCoreApplication.translate("MainWindow", u"Layer 3", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Blocks", None))
        self.geoSpear.setText(QCoreApplication.translate("MainWindow", u"Spear", None))
        self.geoFloor.setText(QCoreApplication.translate("MainWindow", u"Floor", None))
        self.geoWall.setText(QCoreApplication.translate("MainWindow", u"Wall", None))
        self.geoHive.setText(QCoreApplication.translate("MainWindow", u"Fly hive", None))
        self.geoGlass.setText(QCoreApplication.translate("MainWindow", u"Glass", None))
        self.geoCrack.setText(QCoreApplication.translate("MainWindow", u"Crack", None))
        self.geoForbidChains.setText(QCoreApplication.translate("MainWindow", u"Forbid Fly\n"
"Chains", None))
        self.geoBeam.setText(QCoreApplication.translate("MainWindow", u"Beam", None))
        self.geoAir.setText(QCoreApplication.translate("MainWindow", u"Air", None))
        self.geoRock.setText(QCoreApplication.translate("MainWindow", u"Rock", None))
        self.geoSlope.setText(QCoreApplication.translate("MainWindow", u"Slope", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.geo), QCoreApplication.translate("MainWindow", u"GEO", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tiles), QCoreApplication.translate("MainWindow", u"Tiles", None))
    # retranslateUi

